running-elephant/datart

data-providers/src/main/java/datart/data/provider/calcite/SqlNodeUtils.java

fix: sql literal date format #60 #49

fix: sql literal date format 

---

frontend/src/app/pages/DashBoardPage/slice/thunk.ts
frontend/src/app/pages/DashBoardPage/slice/types.ts
frontend/src/app/pages/SharePage/BoardForShare.tsx
frontend/src/app/pages/SharePage/DownloadTaskContainer.tsx
frontend/src/app/pages/SharePage/SharePage.tsx
frontend/src/app/pages/SharePage/StoryPlayerForShare.tsx
frontend/src/app/pages/SharePage/slice/index.ts
frontend/src/app/pages/SharePage/slice/selectors.ts
frontend/src/app/pages/SharePage/slice/thunks.ts
frontend/src/app/pages/SharePage/slice/types.ts
frontend/src/app/pages/StoryBoardPage/Editor/index.tsx
frontend/src/app/pages/StoryBoardPage/Preview/Preview.tsx
frontend/src/app/pages/StoryBoardPage/components/StoryHeader.tsx
frontend/src/app/pages/StoryBoardPage/components/StoryOverLay.tsx
frontend/src/app/pages/StoryBoardPage/components/StoryPageItem.tsx
frontend/src/app/pages/StoryBoardPage/contexts/StoryContext.ts
frontend/src/app/pages/StoryBoardPage/slice/actions.ts
frontend/src/app/pages/StoryBoardPage/slice/index.ts
frontend/src/app/pages/StoryBoardPage/slice/selectors.ts
frontend/src/app/pages/StoryBoardPage/slice/thunks.ts
frontend/src/app/pages/StoryBoardPage/slice/types.ts
frontend/src/app/pages/StoryBoardPage/utils.ts

feat: share storyboard

---

frontend/src/app/pages/SharePage/SharePage.tsx
frontend/src/app/pages/SharePage/sercive.ts
frontend/src/app/pages/SharePage/slice/index.ts
frontend/src/app/pages/SharePage/slice/selectors.ts
frontend/src/app/pages/SharePage/slice/thunks.ts
frontend/src/app/pages/SharePage/slice/types.ts
frontend/src/app/utils/fetch.ts
frontend/src/utils/persistence.ts

fix(chart): fix share page cached password issue,  issue #58

---

data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
data-providers/src/main/java/datart/data/provider/local/LocalDB.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java

fix: Escape quote in LocalDB SQL 
fix: Multiple inserts instead of one in LocalDB
fix: get total count using count sql

bug fix:paging / sql escape 

---

data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java

fix: jdbc param compatible for tidb #122

fix: jdbc param compatible for tidb 

---

data-providers/jdbc-data-provider/src/main/resources/jdbc-driver.yml

The mssql-jdbc  driver's correct configure should like this :
driver-class: com.microsoft.sqlserver.jdbc.SQLServerDriver
url-prefix: jdbc:sqlserver://

fix mssql driver

---

frontend/src/app/pages/MainPage/pages/VariablePage/SubjectForm/index.tsx

fix: incorrect reselect members when editing variable subject relation, issue #151

---

frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDataViewPanel/ChartDataViewPanel.tsx
frontend/src/app/pages/ChartWorkbenchPage/slice/workbenchSlice.ts

fix: view selector state memo problem, #19

---

frontend/src/app/share.tsx

fix(share): echarts_default_theme

fix(share): echarts_default_theme

---

core/src/main/java/datart/core/base/PageInfo.java
core/src/main/java/datart/core/common/JacksonSerializer.java
core/src/main/java/datart/core/data/provider/ExecuteParam.java
core/src/main/java/datart/core/data/provider/QueryScript.java
data-providers/http-data-provider/src/main/java/datart/data/provider/HttpDataProvider.java
data-providers/src/main/java/datart/data/provider/calcite/SqlBuilder.java
data-providers/src/main/java/datart/data/provider/calcite/SqlFunctionRegisterVisitor.java
data-providers/src/main/java/datart/data/provider/calcite/SqlNodeUtils.java
security/src/main/java/datart/security/base/Permission.java
security/src/main/java/datart/security/manager/shiro/ShiroSecurityManager.java
server/src/main/java/datart/server/base/dto/ResponseData.java
server/src/main/java/datart/server/base/params/FolderCreateParam.java
server/src/main/java/datart/server/base/params/FolderUpdateParam.java
server/src/main/java/datart/server/config/WebMvcConfig.java
server/src/main/java/datart/server/service/impl/SysServiceImpl.java
server/src/main/java/datart/server/service/impl/UserServiceImpl.java
server/src/main/resources/application.yml
server/src/main/resources/assembly/assembly.xml

feat: use fastjson as json serializer
fix: response code 400 when user not active
fix: some function can execute in function column #153

feat: use fastjson as json serializer

---

core/src/main/java/datart/core/base/consts/VariableTypeEnum.java
data-providers/http-data-provider/src/main/resources/http-data-provider.json
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
data-providers/src/main/java/datart/data/provider/DefaultDataProvider.java
data-providers/src/main/java/datart/data/provider/jdbc/PermissionVariablePlaceholder.java
data-providers/src/main/java/datart/data/provider/jdbc/QueryVariablePlaceholder.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java
data-providers/src/main/java/datart/data/provider/local/LocalDB.java
data-providers/src/main/java/datart/data/provider/script/VariablePlaceholder.java

feat: replace expression variables before sql parse
fix: h2 column alias bug
fix: sql parse bug

feat: replace expression variables before sql parse

---

data-providers/file-data-provider/src/main/java/datart/data/provider/FileDataProvider.java
data-providers/file-data-provider/src/main/resources/file-data-provider.json
data-providers/http-data-provider/src/main/java/datart/data/provider/HttpDataFetcher.java
data-providers/http-data-provider/src/main/java/datart/data/provider/HttpDataProvider.java
data-providers/http-data-provider/src/main/java/datart/data/provider/HttpRequestParam.java
data-providers/http-data-provider/src/main/java/datart/data/provider/HttpResponseParser.java
data-providers/http-data-provider/src/main/java/datart/data/provider/ResponseJsonParser.java
data-providers/http-data-provider/src/main/resources/http-data-provider.json
data-providers/src/main/java/datart/data/provider/DefaultDataProvider.java
data-providers/src/main/java/datart/data/provider/local/LocalDB.java
data-providers/src/main/java/datart/data/provider/script/VariablePlaceholder.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java

fix: http data provider schema parse bug #191 
fix: Supports variables outside of expressions

fix: http data provider schema parse bug #191 

---

frontend/src/app/pages/ChartWorkbenchPage/components/ChartHeaderPanel/ChartHeaderPanel.tsx
frontend/src/app/pages/ChartWorkbenchPage/slice/workbenchSlice.ts

fix(fetchChartAction): add widgetChart view.meta #206

fix(fetchChartAction): add widgetChart view.meta #206

---

core/src/main/java/datart/core/base/consts/Const.java
core/src/main/java/datart/core/data/provider/DataProviderConfigTemplate.java
core/src/main/java/datart/core/data/provider/Dataframe.java
core/src/main/java/datart/core/mappers/ext/ViewMapperExt.java
data-providers/file-data-provider/src/main/java/datart/data/provider/FileDataProvider.java
data-providers/file-data-provider/src/main/resources/file-data-provider.json
data-providers/http-data-provider/src/main/resources/http-data-provider.json
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
data-providers/src/main/java/datart/data/provider/DefaultDataProvider.java
data-providers/src/main/java/datart/data/provider/calcite/SqlBuilder.java
data-providers/src/main/java/datart/data/provider/calcite/dialect/H2Dialect.java
data-providers/src/main/java/datart/data/provider/jdbc/DataTypeUtils.java
data-providers/src/main/java/datart/data/provider/jdbc/ResultSetMapper.java
data-providers/src/main/java/datart/data/provider/local/LocalDB.java
server/src/main/java/datart/server/controller/ViewController.java
server/src/main/java/datart/server/controller/VizController.java
server/src/main/java/datart/server/service/ViewService.java
server/src/main/java/datart/server/service/VizService.java
server/src/main/java/datart/server/service/impl/ViewServiceImpl.java
server/src/main/java/datart/server/service/impl/VizServiceImpl.java

feat: Support H2 function table
feat: unarchive viz with index
fix:check children before delete a view
fix: quote H2 table name

feat: Support H2 function table

---

core/src/main/java/datart/core/mappers/ext/StorypageMapperExt.java
server/src/main/java/datart/server/controller/VizController.java
server/src/main/java/datart/server/service/BaseCRUDService.java
server/src/main/java/datart/server/service/StorypageService.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java
server/src/main/java/datart/server/service/impl/StoryboardServiceImpl.java
server/src/main/java/datart/server/service/impl/StorypageServiceImpl.java
server/src/main/java/datart/server/service/impl/ViewServiceImpl.java

fix: delete all references when delete a storyboard
fix: unarchive view chek name bug
fix: unarchive viz param error
fix: during test execution,don't execute count(*) operate #219

fix: during test execution,don't execute count(*) operate

---

data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/OracleDataProviderAdapter.java
data-providers/src/main/java/datart/data/provider/DefaultDataProvider.java
data-providers/src/main/java/datart/data/provider/calcite/dialect/ClickHouseSqlDialectSupport.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java
data-providers/src/main/java/datart/data/provider/local/LocalDB.java
server/src/main/java/datart/server/config/WebExceptionHandler.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java

feat:support sql limit for clickhouse  #219

feat:support sql limit for clickhouse

---

core/src/main/java/datart/core/data/provider/DataProvider.java
core/src/main/java/datart/core/data/provider/DataProviderManager.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/JdbcDataProvider.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/base/JdbcProperties.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/DataSourceFactoryDruidImpl.java
data-providers/jdbc-data-provider/src/main/resources/jdbc-data-provider.json
data-providers/src/main/java/datart/data/provider/ProviderManager.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java
server/src/main/java/datart/server/controller/DataProviderController.java
server/src/main/java/datart/server/service/DataProviderService.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java
server/src/main/java/datart/server/service/impl/SourceServiceImpl.java

fix: presto db connect error 
feat: allow empty user and pwd in jdbc connect property

feat: allow empty user and pwd in jdbc connect property

---

frontend/src/app/components/Chronograph.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/Editor/Toolbar.tsx

feat(View): add chronograph to show query time

---

config/application-config.yml.example
core/src/main/java/datart/core/common/CacheFactory.java
data-providers/file-data-provider/src/main/resources/file-data-provider.json
data-providers/http-data-provider/src/main/resources/http-data-provider.json
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
data-providers/src/main/java/datart/data/provider/DefaultDataProvider.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java
data-providers/src/main/java/datart/data/provider/local/LocalDB.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java

feat: support datasource cache for http/file data provider

---

frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ChartSelectModal.tsx
frontend/src/app/pages/MainPage/slice/utils.ts
frontend/src/globalConstants.ts
frontend/src/utils/utils.ts

remove eslint warnings

---

frontend/src/utils/utils.ts

fix: getExpandedKeys function issue #280

---

frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/SettingJumpModal/FieldsSelect.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/SettingJumpModal/index.tsx

Bug fixes for related fields in jump settings

Bug fixes for related fields in jump settings

---

data-providers/src/main/java/codegen/Parser.jj
data-providers/src/main/java/datart/data/provider/DefaultDataProvider.java
data-providers/src/main/java/datart/data/provider/local/LocalDB.java

fix: support sql any join 
fix: file provider value parse error
fix: set h2 case insensitive

fix: set h2 case insensitive

---

frontend/src/index.tsx

fix: #50 Solve the compatibility problem of replaceAll

fix: #50 Solve the compatibility problem of replaceAll

---

.github/ISSUE_TEMPLATE/bug-report.md

add Version

---

frontend/src/app/components/FormGenerator/Customize/ConditionStylePanel/ConditionalStylePanel.tsx
frontend/src/app/components/FormGenerator/Customize/ConditionStylePanel/add.tsx
frontend/src/app/components/FormGenerator/Customize/ConditionStylePanel/types.ts
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartGraph/BasicTableChart/BasicTableChart.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartGraph/BasicTableChart/conditionStyle.ts
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

fix: conditionStyle conflict problem

---

core/src/main/java/datart/core/base/consts/Const.java
core/src/main/java/datart/core/mappers/ext/VariableMapperExt.java
data-providers/src/main/java/datart/data/provider/local/LocalDB.java
server/pom.xml
server/src/main/java/datart/server/service/VariableService.java
server/src/main/java/datart/server/service/impl/VariableServiceImpl.java
server/src/main/java/datart/server/service/impl/ViewServiceImpl.java

fix: check view reference before delete
fix: delete view reference  when delete a view
fix: server agg bug
fix: email reg exp #370

fix: server aggregate bug

---

frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/ValuesOptionsSetter/CustomOptions.tsx

fix(controller): #368 on select custom optionItem

---

Deployment.md
README.md

添加简易部署流程[Deployment.md] 

---

core/src/main/java/datart/core/common/CacheFactory.java
data-providers/src/main/java/datart/data/provider/calcite/SqlValidateUtils.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java
server/src/main/java/datart/server/service/impl/RedisCacheImpl.java

feat:Optimize SQL syntax hints
fix: rename all buildIn variables
fix: change cache timeout form millisecond to second

fix: change cache timeout form millisecond to second

---

core/src/main/java/datart/core/common/CSVParse.java
core/src/main/java/datart/core/common/DateUtils.java
core/src/main/java/datart/core/data/provider/Column.java
data-providers/src/main/java/datart/data/provider/DefaultDataProvider.java

feat: http and file date provider support date string which time fields are arranged in sequence

feat: support date string which time fields are arranged in sequence

---

frontend/package.json
frontend/src/app/components/ReactFrameComponent/Content.jsx
frontend/src/app/components/ReactFrameComponent/Context.jsx
frontend/src/app/components/ReactFrameComponent/Frame.jsx
frontend/src/app/components/ReactFrameComponent/index.js
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartTools/ChartIFrameContainer.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartTools/ChartLifecycleAdapter.tsx

refactor:ReactFrameComponent 分享的仪表板外链在微信中打不开 #392
fix: remove npm dependencies react-frame-component

fix: remove npm dependencies react-frame-component

---

data-providers/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java
data-providers/src/main/java/datart/data/provider/script/VariablePlaceholder.java
server/src/main/java/datart/server/service/impl/DashboardServiceImpl.java
server/src/main/java/datart/server/service/impl/DatachartServiceImpl.java
server/src/main/java/datart/server/service/impl/FolderServiceImpl.java
server/src/main/java/datart/server/service/impl/ScheduleServiceImpl.java
server/src/main/java/datart/server/service/impl/SourceServiceImpl.java
server/src/main/java/datart/server/service/impl/StoryboardServiceImpl.java

fix: create permission bug
fix: sql parse bug fix #416

fix: sql parse bug fix 

---

server/src/main/java/datart/server/base/dto/DatachartDetailList.java
server/src/main/java/datart/server/service/BaseCRUDService.java
server/src/main/java/datart/server/service/impl/VizServiceImpl.java

fix: viz name check bug
feat:add related variables when get a chart detail

feat:add related variables when get a chart detail

---

data-providers/src/main/java/codegen/Parser.jj
data-providers/src/main/java/datart/data/provider/optimize/DataProviderExecuteOptimizer.java
server/src/main/java/datart/server/service/BaseCRUDService.java
server/src/main/java/datart/server/service/VizCRUDService.java
server/src/main/java/datart/server/service/impl/ScheduleServiceImpl.java
server/src/main/java/datart/server/service/impl/SourceServiceImpl.java
server/src/main/java/datart/server/service/impl/StoryboardServiceImpl.java

feat: support select from a function as table #414 
fix: org check name bug

feat: support select from a function as table

---

frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartGraph/BasicTableChart/BasicTableChart.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartGraph/BasicTableChart/TableComponents.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartGraph/FenZuTableChart/FenZuTableChart.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartTools/ChartIFrameContainer.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartTools/ChartLifecycleAdapter.tsx
frontend/src/app/pages/ChartWorkbenchPage/models/ChartHttpRequest.ts
frontend/src/app/pages/DashBoardPage/components/WidgetCore/DataChartWidget/index.tsx
frontend/src/app/pages/DashBoardPage/components/WidgetProvider/WidgetMethodProvider.tsx
frontend/src/app/pages/DashBoardPage/components/WidgetToolBar/config.ts

问题预览
默认无效果，鼠标移动会有对应提示。
- 联动效果：字体颜色变化
- 跳转效果：字体颜色变化，显示下划线
效果预览

feat: 开放表格的跳转及联动功能

---

frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

style: format json code

---

frontend/package.json

fix: lock ant-design/pro-table version with antd

---

frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/ValuesOptionsSetter/AssistViewFields.tsx

https://github.com/running-elephant/datart/issues/459
make page can edit after click folder.

fix(controller):#459 make page can edit after click folder

---

core/pom.xml
core/src/main/java/datart/core/base/consts/Const.java
data-providers/src/main/java/datart/data/provider/calcite/dialect/ImpalaSqlDialectSupport.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java

fix: datetime parse error in impala #413

fix: datetime parse error in impala

---

frontend/src/app/pages/MainPage/pages/ViewPage/SaveForm.tsx
frontend/src/app/pages/MainPage/pages/VizPage/SaveForm.tsx

fix: 新增“名称”效验表意不明. issue #482

---

frontend/src/app/pages/ChartWorkbenchPage/slice/workbenchSlice.ts

Modify the initialization logic of the aggregation switch

Modify the initialization logic of the aggregation switch

---

frontend/src/app/pages/SharePage/BoardForShare.tsx
frontend/src/app/pages/SharePage/ChartForShare.tsx
frontend/src/app/pages/SharePage/ChartPreviewBoardForShare.tsx
frontend/src/app/pages/SharePage/SharePage.tsx

fix: board in task to image
fix: chartPreview task image

fix: board and chart sent to image in task

---

bin/migrations/migration.1.0.0-beta.0.sql
core/pom.xml
core/src/main/java/datart/core/common/WebUtils.java
data-providers/file-data-provider/pom.xml
data-providers/http-data-provider/pom.xml
data-providers/jdbc-data-provider/pom.xml
data-providers/pom.xml
pom.xml
security/pom.xml
server/pom.xml

feat:update version to 1.0.0-beta.0

fix: schedule job bug fix

---

data-providers/file-data-provider/src/main/resources/file-data-provider.json
data-providers/http-data-provider/src/main/java/datart/data/provider/HttpDataProvider.java

fix:file provider config template bug fix

---

frontend/src/app/pages/MainPage/pages/ViewPage/Sidebar/FolderTree.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Sidebar/Recycle.tsx

fix: 数据视图列表国际化渲染有误

---

core/src/main/java/datart/core/base/consts/Const.java
core/src/main/java/datart/core/common/RequestContext.java
data-providers/src/main/java/codegen/Parser.jj
data-providers/src/main/java/datart/data/provider/calcite/SqlValidateUtils.java
data-providers/src/main/java/datart/data/provider/jdbc/RegexVariableResolver.java
data-providers/src/main/java/datart/data/provider/jdbc/ReplaceVariablePlaceholder.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlOperatorReg.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlParserVariableResolver.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java
server/src/main/java/datart/server/base/dto/ResponseData.java
server/src/main/java/datart/server/config/ControllerResponseAdvice.java
server/src/main/java/datart/server/config/interceptor/LoginInterceptor.java
server/src/main/resources/i18n/datart_i18n.properties
server/src/main/resources/i18n/datart_i18n_en.properties
server/src/main/resources/i18n/datart_i18n_zh.properties

fix: sql parser function name support

feat: fallback support for sql parse error

---

data-providers/src/main/java/codegen/Parser.jj

fix:sql  support bit and 

---

data-providers/src/main/java/codegen/Parser.jj
data-providers/src/main/java/datart/data/provider/calcite/SqlVariableVisitor.java
data-providers/src/main/java/datart/data/provider/script/VariablePlaceholder.java

fix:support DateTime Literal as function name #467 
fix: sql function tosql bug fix  #585

fix: sql function tosql bug fix

---

frontend/src/app/pages/DashBoardPage/pages/Board/slice/index.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/slice/actions/actions.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/slice/thunk.ts
frontend/src/app/pages/DashBoardPage/utils/widget.ts

fix: close issue #588

---

data-providers/src/main/java/codegen/Parser.jj
data-providers/src/main/java/datart/data/provider/script/VariablePlaceholder.java

fix: variable name case insensitive bug fix  #527 
feat:support INSERT as function name #365

fix: variable name case insensitive bug fix

---

data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/OracleDataProviderAdapter.java
data-providers/src/main/java/datart/data/provider/calcite/SpecialSqlCallConverter.java
data-providers/src/main/java/datart/data/provider/calcite/SqlBuilder.java
data-providers/src/main/java/datart/data/provider/calcite/SqlNodeUtils.java
data-providers/src/main/java/datart/data/provider/calcite/SqlValidateUtils.java
data-providers/src/main/java/datart/data/provider/calcite/SqlVariableVisitor.java
data-providers/src/main/java/datart/data/provider/jdbc/FalseVariablePlaceholder.java
data-providers/src/main/java/datart/data/provider/jdbc/PermissionVariablePlaceholder.java
data-providers/src/main/java/datart/data/provider/jdbc/QueryVariablePlaceholder.java
data-providers/src/main/java/datart/data/provider/jdbc/RegexVariableResolver.java
data-providers/src/main/java/datart/data/provider/jdbc/SimpleVariablePlaceholder.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java
data-providers/src/main/java/datart/data/provider/jdbc/TrueVariablePlaceholder.java
data-providers/src/main/java/datart/data/provider/local/LocalDB.java
data-providers/src/main/java/datart/data/provider/script/ScriptRender.java
data-providers/src/main/java/datart/data/provider/script/VariablePlaceholder.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java
server/src/main/resources/i18n/datart_i18n.properties
server/src/main/resources/i18n/datart_i18n_en.properties
server/src/main/resources/i18n/datart_i18n_zh.properties

fix: local db concurrency bug fix
fix: set default unchange case to all sql dialect

feat:refactor variable replace

---

frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/TimeSetter/RelativeTimeSetter.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/ValuesOptionsSetter/AssistViewFields.tsx
frontend/src/app/pages/DashBoardPage/utils/index.ts
frontend/src/app/pages/DashBoardPage/utils/widgetToolKit/__tests__/index.test.ts

refactor: getWidgetControlValues fixbug #641

---

frontend/src/app/pages/MainPage/pages/ViewPage/SaveForm.tsx
frontend/src/app/pages/MainPage/pages/VizPage/SaveForm.tsx

复现姿势
1.新建仪表板
2.输入： 下载png图片测试-李雪宁-支持跳转、联动[未发布]

fix: 名称效验未编码导致接口返回错误信息页面崩溃

---

frontend/src/app/hooks/useCacheWidthHeight.ts
frontend/src/app/hooks/useWidgetRowHeight.ts
frontend/src/app/pages/DashBoardPage/constants.ts
frontend/src/app/pages/DashBoardPage/pages/Board/AutoDashboard/AutoBoardCore.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/AutoEditor/AutoBoardEditor.tsx

refactor: useWidgetRowHeight has MIN_ROW_HEIGHT

feat(board):dynamicRowHeight in autoBoard 💪 

---

core/src/main/java/datart/core/base/consts/Const.java
core/src/main/java/datart/core/base/consts/PlatformSettings.java
core/src/main/java/datart/core/data/provider/ScriptVariable.java
core/src/main/java/datart/core/mappers/ext/OrgSettingsMapperExt.java
data-providers/src/main/java/datart/data/provider/calcite/SqlBuilder.java
data-providers/src/main/java/datart/data/provider/calcite/SqlVariableVisitor.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlSplitter.java
data-providers/src/main/java/datart/data/provider/script/VariablePlaceholder.java
server/src/main/java/datart/server/base/params/DatachartCreateParam.java
server/src/main/java/datart/server/controller/FileController.java
server/src/main/java/datart/server/service/OrgSettingService.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java
server/src/main/java/datart/server/service/impl/DownloadServiceImpl.java
server/src/main/java/datart/server/service/impl/OrgSettingServiceImpl.java

fix: sql split bug fix #594
feat: Allows permission variables to be anywhere

feat: support download limit setting

---

data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
server/src/main/java/datart/server/base/params/CheckNameParam.java
server/src/main/java/datart/server/controller/OrgController.java
server/src/main/java/datart/server/controller/RoleController.java
server/src/main/java/datart/server/controller/ScheduleController.java
server/src/main/java/datart/server/controller/SourceController.java
server/src/main/java/datart/server/controller/VariableController.java
server/src/main/java/datart/server/controller/ViewController.java
server/src/main/java/datart/server/controller/VizController.java

fix:Release JDBC Resource
fix: name check receives parameters from request body

fix: name check receives parameters from request body

---

server/src/main/java/datart/server/config/interceptor/BasicValidRequestInterceptor.java

add custom favicon.ico

---

data-providers/src/main/java/datart/data/provider/calcite/SqlNodeUtils.java
data-providers/src/main/java/datart/data/provider/jdbc/RegexVariableResolver.java
data-providers/src/main/java/datart/data/provider/jdbc/SimpleVariablePlaceholder.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlOperatorReg.java
data-providers/src/test/java/datart/data/provider/ParamFactory.java
data-providers/src/test/java/datart/data/provider/SqlExamples.java
data-providers/src/test/java/datart/data/provider/sql/SqlScriptRenderTest.java
data-providers/src/test/java/datart/data/provider/sql/TestFallback.java

fix: column name will not quoted by default
feat: sql parser test case

fix: column name will not quoted by default

---

core/src/main/java/datart/core/base/consts/Const.java
data-providers/src/main/java/datart/data/provider/base/ParamReplaceException.java
data-providers/src/main/java/datart/data/provider/script/VariablePlaceholder.java

feat: replace variable as string when unknown error occurs

---

core/src/main/java/datart/core/data/provider/Column.java
core/src/main/java/datart/core/entity/Schedule.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
data-providers/src/main/java/codegen/Parser.jj
data-providers/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java

feat:support column foreign keys 
feat:support json_object('k1','v1') and array(exp,exp...)

feat:support json_object('k1','v1') and array(exp,exp...)

---

frontend/src/task.ts

fix(task): polyfill in the first line

---

frontend/src/app/pages/MainPage/pages/VizPage/Main/index.tsx
frontend/src/app/pages/SharePage/SharePage.tsx
frontend/src/styles/globalStyles.ts

style(viz,share): @media (max-width: 575px) .ant-form-item

style(viz,share): @media (max-width: 575px) .ant-form-item

---

frontend/src/app/pages/MainPage/pages/VariablePage/VariableForm.tsx

Reverts running-elephant/datart#669

Revert "fix(Variable): add required validator to permission variable default value"

---

frontend/.stylelintrc
frontend/package.json

chore(deps-dev): bump stylelint from 13.x to 14.x

---

frontend/src/app/components/ChartEditor.tsx
frontend/src/app/components/SaveToDashboard.tsx
frontend/src/app/components/VizHeader/VizHeader.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartHeaderPanel/ChartHeaderPanel.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDataViewPanel/ChartDataViewPanel.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartToolbar/Aggregation.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartWorkbench/ChartWorkbench.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/BoardToolBar/AddChart/ChartWidgetDropdown.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ChartSelectModal.tsx
frontend/src/app/pages/MainPage/pages/VizPage/ChartPreview/ChartPreview.tsx
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

fix: Add a layer of judgment before saving to the dashboard
chore(ChartDataViewPanel.tsx): Use useStateModal instead of Confirm

fix: Add a layer of judgment before saving to the dashboard

---

frontend/src/app/migration/WidgetConfig/migrateWidgets.ts
frontend/src/app/migration/__tests__/migrateWidgets.test.ts
frontend/src/app/migration/constants.ts
frontend/src/app/migration/migrateWidgets.ts
frontend/src/app/pages/DashBoardPage/pages/Board/slice/asyncActions.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/slice/thunk.ts
frontend/src/app/pages/DashBoardPage/utils/widget.ts
frontend/src/task.ts

refactor:migrateWidgets
test:refactor:migrateWidgets

refactor:migrateWidgets

---

data-providers/jdbc-data-provider/src/main/java/datart/data/provider/JdbcDataProvider.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/resources/jdbc-data-provider.json
data-providers/src/main/java/datart/data/provider/ProviderManager.java
data-providers/src/main/java/datart/data/provider/calcite/SqlValidateUtils.java
data-providers/src/main/java/datart/data/provider/jdbc/JdbcProperties.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java
server/src/main/resources/i18n/datart_i18n.properties
server/src/main/resources/i18n/datart_i18n_en.properties
server/src/main/resources/i18n/datart_i18n_zh.properties

feat: jdbc data provider supports executable configuration for special sql

feat: supports executable configuration for special sql

---

frontend/src/app/migration/BoardConfig/migrateBoardConfig.ts
frontend/src/app/migration/__tests__/migrateBoardConfig.test.ts
frontend/src/app/pages/DashBoardPage/pages/Board/slice/types.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/DeviceList/DeviceList.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/SlideSetting/BoardSetting.tsx
frontend/src/app/pages/DashBoardPage/utils/board.ts

[refactor(board): BoardSetting]
[test: migrateBoardConfig]

feat(board):migrateBoardConfig

---

frontend/package.json

https://github.com/facebook/create-react-app/issues/11880

fix: workaround of cra hot reload issue

---

data-providers/jdbc-data-provider/src/main/java/datart/data/provider/JdbcDataProvider.java
server/src/main/java/datart/server/config/interceptor/BasicValidRequestInterceptor.java

add basic valid request resource

fix: jdbc data provider parameter bug fix

---

frontend/src/app/pages/MainPage/pages/VizPage/hooks/useAddViz.ts
frontend/src/app/pages/SharePage/slice/thunks.ts
frontend/src/index.tsx
frontend/src/share.tsx

fix: change import order of antd.less
fix: Do not close the popup box after the api reports an error

fix: change import order of antd.less

---

frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartConfigPanel/ChartConfigPanel.tsx

fix: Solve the problem that the scroll bar is not displayed

fix: Solve the problem that the scroll bar is not displayed

---

server/src/main/java/datart/server/service/impl/EmailJob.java

 fix: Cannot create an email task with multiple email addresses

---

frontend/src/app/components/ChartEditor.tsx

fix: Edit charts page does not select default chart

fix: Edit charts page does not select default chart

---

frontend/src/app/pages/DashBoardPage/components/WidgetProvider/WidgetMethodProvider.tsx

fix(board): clickJump&toLinkingWidgets

---

frontend/src/app/pages/MainPage/pages/VizPage/index.tsx

fix: dashboard does not refresh when sidebar is collapsed

fix: dashboard does not refresh when sidebar is collapsed

---

frontend/src/app/components/SaveToDashboard.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartHeaderPanel/ChartHeaderPanel.tsx
frontend/src/app/pages/MainPage/pages/VizPage/SaveForm.tsx
frontend/src/app/pages/MainPage/pages/VizPage/slice/index.ts
frontend/src/app/pages/MainPage/pages/VizPage/slice/selectors.ts
frontend/src/app/pages/MainPage/pages/VizPage/slice/types.ts

chore: Reduce unnecessary folder api requests

chore: Reduce unnecessary folder api requests

---

frontend/src/app/pages/MainPage/index.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/hooks/useStartAnalysis.tsx
frontend/src/app/pages/MainPage/pages/VizPage/ChartPreview/ChartPreview.tsx
frontend/src/app/pages/MainPage/pages/VizPage/Sidebar/Folders/index.tsx

fix: chartEditor page history state changed to search

fix: chartEditor page history state changed to search

---

frontend/src/app/pages/DashBoardPage/pages/BoardEditor/index.tsx

fix(board): closeChartEditor onBoardEditor destroy

---

config/jdbc-driver-ext.yml
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/JdbcDataProvider.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/DataSourceFactoryDruidImpl.java
data-providers/src/main/java/datart/data/provider/calcite/SqlBuilder.java
data-providers/src/main/java/datart/data/provider/calcite/SqlNodeUtils.java
data-providers/src/main/java/datart/data/provider/jdbc/DataTypeUtils.java
data-providers/src/main/java/datart/data/provider/jdbc/JdbcDriverInfo.java
data-providers/src/main/java/datart/data/provider/jdbc/SimpleVariablePlaceholder.java
data-providers/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java
data-providers/src/main/java/datart/data/provider/script/ScriptRender.java
data-providers/src/main/java/datart/data/provider/script/VariablePlaceholder.java

feat: support quote config for sql identifiers,sql identifier will be quoted by default except oracle  #692

feat: support quote config for sql identifiers

---

frontend/src/app/hooks/useVisibleHidden.ts
frontend/src/app/pages/DashBoardPage/pages/Board/AutoDashboard/AutoBoardCore.tsx
frontend/src/app/pages/DashBoardPage/pages/Board/FreeDashboard/FreeBoardCore.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/AutoEditor/AutoBoardEditor.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/FreeEditor/FreeEditorWrapper.tsx

chore: render Board on init hide in hack way

---

frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDraggable/ChartDraggableTargetContainer.tsx
frontend/src/app/pages/ChartWorkbenchPage/slice/workbenchSlice.ts

fix: add aggregation switch defaultValue

fix: add aggregation switch defaultValue

---

data-providers/src/main/java/datart/data/provider/calcite/SqlValidateUtils.java
server/src/main/java/datart/server/config/WebSecurityConfig.java
server/src/main/java/datart/server/controller/ThirdPartyAuthController.java
server/src/main/resources/application.yml

fix: compatible with users not using oAuth2

---

frontend/src/app/migration/StoryConfig/migrateStoryConfig.ts
frontend/src/app/migration/StoryConfig/migrateStoryPageConfig.ts
frontend/src/app/migration/__tests__/migrateStoryConfig.test.ts
frontend/src/app/migration/__tests__/migrateStoryPageConfig.test.ts

fix(story): storyConfig

---

frontend/src/app/pages/DashBoardPage/components/BoardProvider/BoardActionProvider.tsx
frontend/src/app/pages/DashBoardPage/components/BoardProvider/BoardConfigProvider.tsx
frontend/src/app/pages/DashBoardPage/components/FreeBoardBackground.tsx
frontend/src/app/pages/DashBoardPage/contexts/BoardActionContext.ts
frontend/src/app/pages/DashBoardPage/contexts/BoardConfigContext.ts
frontend/src/app/pages/DashBoardPage/pages/Board/AutoDashboard/AutoBoardCore.tsx
frontend/src/app/pages/DashBoardPage/pages/Board/FreeDashboard/FreeBoardCore.tsx
frontend/src/app/pages/DashBoardPage/pages/Board/slice/types.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/AutoEditor/AutoBoardEditor.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/FreeEditor/FreeEditorWrapper.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/BoardToolBar/AddControler/AddControler.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/BoardToolBar/AllowOverlap.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/BoardToolBar/ToolBar.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/SlideSetting/BoardSetting.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/index.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/slice/childSlice/stackSlice.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/slice/index.ts
frontend/src/app/pages/DashBoardPage/utils/board.ts
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

https://user-images.githubusercontent.com/23504234/155460251-e1c5e49a-4946-470e-ae55-eec463bb47c8.mp4

feat(board): widget overlap in AutoBoard

---

core/src/main/java/datart/core/base/consts/Const.java
core/src/main/java/datart/core/common/POIUtils.java
server/src/main/java/datart/server/service/impl/DownloadServiceImpl.java

fix: optimize fileName and fix download bug

fix: optimize fileName and fix download bug

---

frontend/src/app/components/ChartGraph/BasicTableChart/BasicTableChart.tsx

fix: table header group

---

frontend/src/share.tsx
frontend/src/task.ts

fix:  polyfill  replace-all

---

frontend/src/app/components/ChartEditor.tsx
frontend/src/app/pages/DashBoardPage/components/WidgetToolBar/index.tsx

fix: Error caused by no config in dataview

fix: Error caused by no config in dataview

---

frontend/src/app/utils/chartHelper.ts

fix:(Chart)fix some tooltip function

fix:(Chart)fix some tooltip function

---

Dockerfile
config/jdbc-driver-ext.yml
config/profiles/application-config.yml
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/DorisDataProviderAdapter.java
data-providers/src/test/java/datart/data/provider/SqlExamples.java
data-providers/src/test/java/datart/data/provider/SqlTestEntity.java
data-providers/src/test/java/datart/data/provider/sql/TestFallback.java
server/pom.xml
server/src/main/java/datart/server/common/PoiConvertUtils.java
server/src/main/java/datart/server/job/ScheduleJob.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java
server/src/main/java/datart/server/service/impl/DownloadServiceImpl.java
server/src/main/java/datart/server/service/impl/UserServiceImpl.java
server/src/main/resources/application-demo.yml
server/src/main/resources/assembly/assembly.xml
server/src/main/resources/db/migration/V2022.02.19__1.0.0.beta.2.sql

feat: add sql test case
feat: add doris jdbc driver

fix: public variable with expression as default value bug fix

---

core/src/main/java/datart/core/entity/ext/SourceDetail.java
core/src/main/java/datart/core/mappers/ext/SourceSchemasMapperExt.java
server/src/main/java/datart/server/controller/SourceController.java
server/src/main/java/datart/server/job/SchemaSyncJob.java
server/src/main/java/datart/server/service/impl/SourceServiceImpl.java

feat: Synchronizes schemas async when updating or creating sources

feat: add schema update time in source schema api

---

core/src/main/java/datart/core/common/POIUtils.java
core/src/main/java/datart/core/entity/poi/format/PoiNumFormat.java
data-providers/src/main/java/datart/data/provider/jdbc/RegexVariableResolver.java
server/src/main/java/datart/server/common/PoiConvertUtils.java

fix: download excel cellstyle max number limit and column alias

fix: download excel bug and column alias

---

data-providers/src/main/java/datart/data/provider/freemarker/FreemarkerContext.java
data-providers/src/main/java/datart/data/provider/freemarker/StringTemplateLoader.java
server/src/main/java/datart/server/config/CustomPropertiesValidate.java

fix: Freemarker multi thread bug fix #809 
fix: datart.conf is optional

fix: Freemarker multi thread bug fix

---

data-providers/src/main/java/codegen/Parser.jj
server/src/main/java/datart/server/base/params/ViewExecuteParam.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java

fix: support function name [day]

fix: execute bug fix

---

frontend/src/app/components/VizOperationMenu/components/ShareLinkModal.tsx
frontend/src/app/pages/DashBoardPage/components/WidgetCore/MediaWidget/TimerWidget/index.tsx
frontend/src/app/pages/DashBoardPage/pages/Board/index.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/index.tsx
frontend/src/app/pages/DashBoardPage/utils/index.ts
frontend/src/app/pages/LoginPage/LoginForm.tsx
frontend/src/app/pages/MainPage/pages/VizPage/ChartPreview/components/ControllerPanel/ControllerPanel.tsx
frontend/src/app/pages/MainPage/pages/VizPage/ChartPreview/components/ControllerPanel/components/index.ts
frontend/src/app/slice/index.ts
frontend/src/app/slice/thunks.ts

fix: Eliminate prefixI18N in utils.js
style: beautify code(prettier)

fix: Eliminate prefixI18N in utils.js

---

frontend/src/app/components/ChartGraph/BasicRichText/ChartRichTextAdapter.tsx

fix: editor link not working issue.#950

---

frontend/src/app/components/ChartEditor.tsx
frontend/src/app/migration/ViewConfig/migrationViewDetailConfig.ts
frontend/src/app/migration/__tests__/migrationViewDetailConfig.test.ts
frontend/src/app/pages/ChartWorkbenchPage/components/ChartHeaderPanel/ChartHeaderPanel.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartPresentPanel/components/Chart404Graph.tsx
frontend/src/app/pages/ChartWorkbenchPage/slice/workbenchSlice.ts
frontend/src/app/pages/MainPage/pages/ViewPage/Main/Editor/SQLEditor.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/SaveForm.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Sidebar/index.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/hooks/useSaveAsView.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/slice/thunks.ts
frontend/src/app/pages/MainPage/pages/VizPage/ChartPreview/ChartPreview.tsx
frontend/src/styles/__tests__/media.test.ts

fix: migration view config
test: add migrationViewDetailConfig test

add migrationViewDetailConfig test and migration view config

---

config/logback.xml
core/pom.xml
data-providers/file-data-provider/pom.xml
data-providers/http-data-provider/pom.xml
data-providers/jdbc-data-provider/pom.xml
data-providers/pom.xml
data-providers/src/main/java/datart/data/provider/calcite/SqlParserUtils.java
pom.xml
security/pom.xml
server/pom.xml
server/src/main/java/datart/server/config/interceptor/BasicValidRequestInterceptor.java

fix: function column casing bugfix

---

frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/ValuesOptionsSetter/ValuesOptionsSetter.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/slice/thunk.ts
frontend/src/app/pages/DashBoardPage/utils/index.ts

fix : chart with no view eg richTextChart

fix: getViewOption view model by transformMeta

---

frontend/src/app/pages/SharePage/BoardForShare.tsx
frontend/src/app/pages/SharePage/SharePage.tsx
frontend/src/app/pages/SharePage/TitleForShare.tsx
frontend/src/share.tsx

https://user-images.githubusercontent.com/23504234/158552786-64270f04-b944-4a46-9868-c4b637e8daa6.mp4

feat:TitleForShare

---

frontend/src/app/pages/DashBoardPage/constants.ts

fix: add SqlOperator [Contain,NotContain]

---

frontend/public/custom-chart-plugins/demo-custom-line-chart.js
frontend/src/app/components/ChartGraph/BasicLineChart/BasicLineChart.ts
frontend/src/app/components/ChartGraph/BasicLineChart/config.ts

undefined null value no longer take 0

feat:(Chart)add line connectNulls style

---

data-providers/src/main/java/datart/data/provider/calcite/SqlBuilder.java

Changed the sequence of the group by and aggregators. Excel export no longer has aggregated columns in front.
Please review and proceed if okay.

#883: Excel download data columns sequence is different from table visualisation

---

frontend/src/app/pages/DashBoardPage/components/BoardProvider/BoardActionProvider.tsx
frontend/src/app/pages/DashBoardPage/hooks/useBoardEditorHotkeys.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/BoardToolBar/BoardToolBar.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/BoardToolBar/BoardToolRights.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/BoardToolBar/DelWidgetsBtn.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/BoardToolBar/DeviceSwitch/DeviceSwitcher.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/BoardToolBar/ShortcutKeys.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/BoardToolBar/ToolBar.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/slice/actions/actions.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/slice/childSlice/stackSlice.ts
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

feat: board Hotkeys map

---

frontend/src/app/pages/MainPage/pages/ViewPage/slice/index.ts
frontend/src/app/pages/MainPage/pages/ViewPage/slice/thunks.ts
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json
frontend/src/utils/utils.ts

fix(View): execute test error message process improvements

---

core/src/main/java/datart/core/base/consts/AttachmentType.java
core/src/main/java/datart/core/common/Application.java
core/src/main/java/datart/core/common/FileUtils.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/JdbcDataProvider.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/MsSqlDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/resources/jdbc-driver.yml
security/src/main/java/datart/security/base/ResourceType.java
server/src/main/java/datart/server/base/params/DownloadCreateParam.java
server/src/main/java/datart/server/base/params/UserAddParam.java
server/src/main/java/datart/server/base/params/UserUpdateByIdParam.java
server/src/main/java/datart/server/base/params/ViewExecuteParam.java
server/src/main/java/datart/server/common/JsParserUtils.java
server/src/main/java/datart/server/controller/UserController.java
server/src/main/java/datart/server/job/EmailJob.java
server/src/main/java/datart/server/job/ScheduleJob.java
server/src/main/java/datart/server/service/AttachmentService.java
server/src/main/java/datart/server/service/UserService.java
server/src/main/java/datart/server/service/VizService.java
server/src/main/java/datart/server/service/impl/AttachmentExcelServiceImpl.java
server/src/main/java/datart/server/service/impl/AttachmentImageServiceImpl.java
server/src/main/java/datart/server/service/impl/AttachmentPdfServiceImpl.java
server/src/main/java/datart/server/service/impl/DownloadServiceImpl.java
server/src/main/java/datart/server/service/impl/UserServiceImpl.java
server/src/main/java/datart/server/service/impl/VizServiceImpl.java

- fill common databases default connect value
- schedule image insert into email
- download image and pdf tianyabing

feat: download image and pdf 

---

bin/datart-server.sh

Added check on BASE_DIR of running datart process to support multiple datart-server on same box.
Please review and approve PR if good to go. Thank you.

Run multiple datart-server.sh on same box

---

frontend/src/app/pages/SharePage/ShareChart.tsx
frontend/src/app/pages/SharePage/ShareDashboard.tsx
frontend/src/app/pages/SharePage/ShareStoryPlayer.tsx
frontend/src/app/pages/SharePage/slice/thunks.ts

fix: Optimize the logic of sharing page login

fix: Optimize the logic of sharing page login

---

frontend/src/app/pages/DashBoardPage/pages/Board/AutoDashboard/AutoBoardCore.tsx

fix: Fix the problem that innerRef causes server packaging to fail

fix: Fix the problem that innerRef causes server packaging to fail

---

core/src/main/java/datart/core/common/ClassTransformer.java
server/src/main/java/datart/DatartServerApplication.java

fix: Database migration failure caused by account permission
fix: Function names are default uppercase #998

fix: Function names are default uppercase

---

config/datart.conf
config/profiles/application-config.yml

Added paramters to allow config of SSL if valid keystore is available. Please review and approve pull request if ok to proceed.

Added parameters for SSL

---

config/profiles/application-config.yml
core/pom.xml
data-providers/file-data-provider/pom.xml
data-providers/http-data-provider/pom.xml
data-providers/jdbc-data-provider/pom.xml
data-providers/pom.xml
pom.xml
security/pom.xml
server/pom.xml
server/src/main/resources/db/migration/V2022.03.14__1.0.0.beta.3.sql

update version
update application-config

Feat：update version

---

frontend/src/app/components/ChartDrill/ChartDrillContextMenu.tsx
frontend/src/app/components/ChartEditor.tsx
frontend/src/app/components/ChartGraph/BasicBarChart/BasicBarChart.tsx
frontend/src/app/components/ChartIFrameContainer/ChartIFrameContainer.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartPresentPanel/ChartPresentPanel.tsx
frontend/src/app/utils/chartHelper.ts

Date Level supports all charts
The bug that the switch date level button is not displayed when switching to default date
Clear all temporary data when switching charts

 Date Level supports all charts 

---

server/src/main/java/datart/server/service/BaseCRUDService.java
server/src/main/java/datart/server/service/impl/ExternalRegisterServiceImpl.java
server/src/main/java/datart/server/service/impl/UserServiceImpl.java
server/src/main/resources/db/migration/V2022.03.14__1.0.0.beta.3.sql

ldap user login.
db migration optimize.
restore deleted data source.

fix: ldap user login

---

core/src/main/java/datart/core/entity/Source.java
core/src/main/java/datart/core/entity/Storyboard.java
core/src/main/java/datart/core/mappers/StoryboardMapper.java
core/src/main/java/datart/core/mappers/StoryboardSqlProvider.java
server/src/main/java/datart/server/base/params/ScheduleBaseUpdateParam.java
server/src/main/java/datart/server/base/params/ScheduleUpdateParam.java
server/src/main/java/datart/server/base/params/SourceBaseUpdateParam.java
server/src/main/java/datart/server/base/params/SourceCreateParam.java
server/src/main/java/datart/server/base/params/SourceUpdateParam.java
server/src/main/java/datart/server/base/params/StoryboardBaseUpdateParam.java
server/src/main/java/datart/server/base/params/StoryboardCreateParam.java
server/src/main/java/datart/server/base/params/StoryboardUpdateParam.java
server/src/main/java/datart/server/config/ExternalRegisterRedirectStrategy.java
server/src/main/java/datart/server/config/Oauth2AuthenticationSuccessHandler.java
server/src/main/java/datart/server/controller/ScheduleController.java
server/src/main/java/datart/server/controller/SourceController.java
server/src/main/java/datart/server/controller/VizController.java
server/src/main/java/datart/server/service/ScheduleService.java
server/src/main/java/datart/server/service/SourceService.java
server/src/main/java/datart/server/service/StoryboardService.java
server/src/main/java/datart/server/service/VizService.java
server/src/main/java/datart/server/service/impl/ScheduleServiceImpl.java
server/src/main/java/datart/server/service/impl/SourceServiceImpl.java
server/src/main/java/datart/server/service/impl/StoryboardServiceImpl.java
server/src/main/java/datart/server/service/impl/VizServiceImpl.java

source、schedule、storyboard support folder
oauth2 add error redirect

feat: source、schedule、storyboard support folder

---

frontend/src/app/components/ChartIFrameContainer/ChartIFrameEventBroker.ts
frontend/src/app/pages/MainPage/pages/VizPage/slice/index.ts

fix chart preview conditional style issue #1281 

---

frontend/src/app/pages/DashBoardPage/utils/__tests__/index.test.tsx

test: Fix getDefaultWidgetName test

test: Fix getDefaultWidgetName test

---

data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/HiveDataProviderAdapter.java
server/src/main/java/datart/server/service/impl/StorypageServiceImpl.java

fix: hive show all databases #1322 
fix: storyboard edit auth #1347

fix: show hive databases and storyboard auth

---

core/src/main/java/datart/core/common/POIUtils.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/PrestoDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/resources/jdbc-driver.yml
server/src/main/java/datart/server/base/dto/chart/ChartColumn.java
server/src/main/java/datart/server/base/dto/chart/ChartConfigDTO.java
server/src/main/java/datart/server/common/PoiConvertUtils.java
server/src/main/java/datart/server/job/EmailJob.java
server/src/main/java/datart/server/job/ScheduleJob.java
server/src/main/java/datart/server/service/AttachmentService.java
server/src/main/java/datart/server/service/impl/DownloadServiceImpl.java

fix: mail content inline image tag #1366
fix: Presto sync database info #1368
optimize: excel download column alias and type

fix: mail img tag & Presto sync database info

---

core/src/main/java/datart/core/common/SQLUtils.java
core/src/main/java/datart/core/mappers/ext/CRUDMapper.java
pom.xml

fix: SQL Injection

---

server/src/main/resources/assembly/assembly.xml

Solve the problem that the package zip of the assembly file is stuck.

fix: assembly packaging configuration

---

frontend/src/app/pages/MainPage/Navbar/index.tsx
frontend/src/app/pages/MainPage/index.tsx
frontend/src/app/pages/MainPage/pages/ExportPage/ExportSelector.tsx
frontend/src/app/pages/MainPage/pages/ExportPage/index.tsx
frontend/src/app/pages/MainPage/pages/ExportPage/utils.ts
frontend/src/app/pages/MainPage/pages/ImportPage/FileUpload.tsx
frontend/src/app/pages/MainPage/pages/ImportPage/index.tsx
frontend/src/app/pages/MainPage/pages/ImportPage/utils.tsx
frontend/src/app/pages/MainPage/pages/PermissionPage/slice/index.tsx
frontend/src/globalConstants.ts
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

feat: export and import datart file

---

frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDataViewPanel/components/ChartComputedFieldSettingPanel.tsx

fix: Little more precision for agg func checks

---

frontend/src/locales/en/translation.json

Resubmitted, please review for issue #1470

Corrected typo for Create View

---

frontend/src/app/components/ChartGraph/Scorecard/config.ts

Please help review this small change. This is for https://github.com/running-elephant/datart/issues/1478

Corrected inconsistenies for style menu labels in Score Chart

---

core/src/main/java/datart/core/common/WebUtils.java
data-providers/data-provider-base/src/main/java/datart/data/provider/calcite/custom/CustomSqlTypeName.java
data-providers/data-provider-base/src/main/java/datart/data/provider/calcite/dialect/HiveSqlStdOperatorSupport.java
data-providers/data-provider-base/src/main/java/datart/data/provider/calcite/dialect/ImpalaSqlDialectSupport.java
data-providers/data-provider-base/src/main/java/datart/data/provider/calcite/dialect/MsSqlStdOperatorSupport.java
data-providers/data-provider-base/src/main/java/datart/data/provider/calcite/dialect/MysqlSqlStdOperatorSupport.java
data-providers/data-provider-base/src/main/java/datart/data/provider/calcite/dialect/OracleSqlStdOperatorSupport.java
data-providers/data-provider-base/src/main/java/datart/data/provider/jdbc/DataTypeUtils.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/ClickHouseDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/DmDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/HiveDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/ImpalaDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/MsSqlDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/OracleDataProviderAdapter.java
data-providers/jdbc-data-provider/src/main/resources/jdbc-driver.yml

refactor: sync database info
fix: boolean type show and hive date type recognize
Date aggregate support hive/impala
webdriver quit

refactor: sync database info 

---

frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/ValuesOptionsSetter/CustomOptions.tsx
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

This is for https://github.com/running-elephant/datart/issues/1517
Please help review. Thank you!

Added i18n support for dashboard controller custom option

---

core/src/main/java/datart/core/common/POIUtils.java
core/src/main/java/datart/core/data/provider/Column.java
core/src/main/java/datart/core/data/provider/TableInfo.java
data-providers/data-provider-base/src/main/java/datart/data/provider/DefaultDataProvider.java
data-providers/data-provider-base/src/main/java/datart/data/provider/calcite/SqlBuilder.java
data-providers/data-provider-base/src/main/java/datart/data/provider/jdbc/ResultSetMapper.java
data-providers/data-provider-base/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java
data-providers/data-provider-base/src/main/java/datart/data/provider/local/LocalDB.java
data-providers/file-data-provider/src/main/java/datart/data/provider/FileDataProvider.java
data-providers/http-data-provider/src/main/java/datart/data/provider/ResponseJsonParser.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java
security/src/main/java/datart/security/base/JwtToken.java
security/src/main/java/datart/security/manager/shiro/ShiroSecurityManager.java
security/src/main/java/datart/security/util/JwtUtils.java
server/src/main/java/datart/server/base/params/ViewCreateParam.java
server/src/main/java/datart/server/common/PoiConvertUtils.java
server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java
server/src/main/java/datart/server/service/impl/ExternalRegisterServiceImpl.java
server/src/main/java/datart/server/service/impl/MailServiceImpl.java
server/src/main/java/datart/server/service/impl/ScheduleServiceImpl.java
server/src/main/java/datart/server/service/impl/UserServiceImpl.java
server/src/main/resources/i18n/datart_i18n.properties
server/src/main/resources/i18n/datart_i18n_en.properties
server/src/main/resources/i18n/datart_i18n_zh.properties

fix: http response parser bugfix #1536

fix: http response parser bugfix

---

frontend/src/app/components/Brand/LayoutWithBrand.tsx
frontend/src/app/components/ListTitle/AddButton.tsx
frontend/src/app/components/ListTitle/index.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/components/SelectDataSource.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/components/SelectJoinColumns.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/components/SelectJoinType.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/index.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/constants.ts
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

1. Rollback auth form styles
2. Fix split line incorrect above add dropdown list
3. Improve partial table view styles

chore: improve partial table view styles

---

frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/components/SelectDataSource.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/components/SelectJoinColumns.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/components/SelectJoinType.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/index.tsx

1. improve table select style
2. improve naming
- tableJSON -> structure
- dataSheet -> tableSchema
- callbackFn -> onChange
- renderType
- READ -> READONLY
- OPERATE -> MANAGE

chore(View): improve table view styles and naming

---

frontend/src/locales/en/translation.json

Hello,
Minor typo. This is for https://github.com/running-elephant/datart/issues/1557
Please help review. Thank you!

Corrected wrong button description

---

frontend/src/app/pages/MainPage/pages/ViewPage/components/SelectViewType.tsx
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

chore: improve view type select page styles

---

frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDataViewPanel/components/ChartComputedFieldSettingPanel.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/components/SelectDataSource.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/components/SelectJoinColumns.tsx

feat: add name fields for  create computedFields

feat: add name fields for  create computedFields

---

core/pom.xml
data-providers/data-provider-base/pom.xml
data-providers/file-data-provider/pom.xml
data-providers/http-data-provider/pom.xml
data-providers/jdbc-data-provider/pom.xml
data-providers/jdbc-data-provider/src/test/java/datart/data/provider/sql/SqlScriptRenderTest.java
data-providers/pom.xml
pom.xml
security/pom.xml
server/pom.xml
server/src/main/resources/db/migration/R2022.05.07__1.0.0.beta.4.sql
server/src/main/resources/db/migration/V2022.05.07__1.0.0.beta.4.sql

feat: update version to 1.0.0-beta.4

---

frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/utils.ts
frontend/src/app/pages/DashBoardPage/utils/widget.ts

fix: change view sorting bug

---

frontend/src/app/pages/ChartWorkbenchPage/slice/index.ts

fix: Add a judgment that viewComputer is empty

fix: Add a judgment that viewComputer is empty

---

Dockerfile
core/src/main/java/datart/core/data/provider/ExecuteParam.java
data-providers/data-provider-base/src/main/java/datart/data/provider/calcite/QueryScriptProcessResult.java
data-providers/data-provider-base/src/main/java/datart/data/provider/calcite/SqlBuilder.java
data-providers/data-provider-base/src/main/java/datart/data/provider/jdbc/SqlScriptRender.java
server/src/main/resources/application.yml

fix: update default config

---

frontend/src/app/pages/DashBoardPage/pages/Board/slice/types.ts
frontend/src/locales/en/translation.json

Hi
This is for https://github.com/running-elephant/datart/issues/1658
Please help to review. Thank you!

Fix english inconsistencies and reword few texts

---

frontend/src/app/components/FormGenerator/Customize/ListTemplatePanel.tsx

fix: listTemplate样式优化

---

frontend/src/app/utils/internalChartHelper.ts

问题如视频所示
不过因为改动的位置是datart最为核心的代码，希望各位大佬可以告知是否可以这样改，或者说有更优的方式
https://user-images.githubusercontent.com/95753485/179494290-3a0d1391-5061-466f-a8b4-cb95d40c65c9.mp4

fix: widget config func类型的属性丢失的问题

---

frontend/src/app/pages/DashBoardPage/utils/widget.ts

fix: Add the judgment that the datachart in the config in the widget is empty

fix: Add the judgment that the datachart in the config in the widget is empty

---

frontend/src/app/components/ChartEditor.tsx
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

Hi,
This is for https://github.com/running-elephant/datart/issues/1762
Please help review. Thank you!

Added i18n to viz save confirmation dialog

---

frontend/src/app/pages/MainPage/pages/SourcePage/SourceDetailPage/ConfigComponent/ArrayConfig.tsx
frontend/src/app/pages/MainPage/pages/SourcePage/SourceDetailPage/ConfigComponent/FileUpload.tsx
frontend/src/app/pages/MainPage/pages/SourcePage/SourceDetailPage/ConfigComponent/index.tsx

feat: 数据源-如果没有填写表名，自动用文件名填充表名

---

frontend/src/app/components/ChartGraph/BasicBarChart/config.ts
frontend/src/app/components/ChartGraph/BasicRadarChart/config.ts
frontend/src/app/components/ChartGraph/ClusterBarChart/config.ts
frontend/src/app/components/ChartGraph/ClusterColumnChart/config.ts
frontend/src/app/components/ChartGraph/PercentageStackBarChart/config.ts
frontend/src/app/components/ChartGraph/PercentageStackColumnChart/config.ts
frontend/src/app/components/ChartGraph/StackBarChart/config.ts
frontend/src/app/components/ChartGraph/StackColumnChart/config.ts
frontend/src/app/components/ChartGraph/WaterfallChart/config.ts

fix: border radius can't be negative

---

frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/components/SelectDataSource.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/components/SelectJoinColumns.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/index.tsx

The data does not change when switching the structure view

fix: issue #1759

---

server/src/main/java/datart/server/service/AttachmentService.java
server/src/main/java/datart/server/service/impl/AttachmentImageServiceImpl.java
server/src/main/java/datart/server/service/impl/AttachmentPdfServiceImpl.java
server/src/main/java/datart/server/service/impl/ShareServiceImpl.java
server/src/main/java/datart/server/service/impl/VizServiceImpl.java
server/src/main/resources/db/migration/R2022.08.05__1.0.0.rc.1.sql
server/src/main/resources/db/migration/V2022.08.05__1.0.0.rc.1.sql

fix: schedule task create share bugfix #1798

fix: schedule task create share bugfix

---

frontend/src/app/components/ChartGraph/BasicDoubleYChart/BasicDoubleYChart.tsx
frontend/src/app/components/ChartGraph/BasicFunnelChart/BasicFunnelChart.tsx
frontend/src/app/components/ChartGraph/BasicFunnelChart/types.ts
frontend/src/app/components/ChartGraph/WaterfallChart/WaterfallChart.tsx

feat: 瀑布图、双Y轴图、漏斗图：隐藏重叠标签

---

frontend/src/app/components/ChartGraph/PivotSheetChart/config.ts

Hi,
This is for https://github.com/running-elephant/datart/issues/1842
Please help review and approve if ok to proceed. Thank you.

Rename pivot row header column name to 'Metric', issue #1842

---

frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDataViewPanel/ChartDataViewPanel.tsx

style: view name is too long to hide

---

frontend/src/app/pages/MainPage/pages/SourcePage/SourceDetailPage/ConfigComponent/ArrayConfig.tsx

修复FILE和HTTP类型数据源，编辑表，并且修改配置后，会添加一条脏数据问题，对应的issue: #1878

fix(ArrayConfig.tsx): 修复FILE和HTTP类型数据源，编辑表，并且修改配置后，会添加一条脏数据问题【#1878】

---

server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java

增加多parseDataProviderConfig 方法的@Override标识和初始化hashMap容量，属于代码小优化，主要是@Override 这个没加

refactor: refactor parseDataProviderConfig method add @Override

---

frontend/src/locales/en/translation.json

Hi
This is for https://github.com/running-elephant/datart/issues/1903
Please help review and approve if ok to proceed. Thank you.

Switch view dialog message enhancement for English

---

server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java

fix: fix null exception when name variable is null 

---

frontend/src/app/pages/DashBoardPage/pages/BoardEditor/AutoEditor/AutoBoardEditor.tsx

fix: auto dashboard mobile viewpoint overflow issue

---

data-providers/data-provider-base/src/main/java/datart/data/provider/ProviderManager.java
data-providers/data-provider-base/src/main/java/datart/data/provider/local/LocalDB.java
server/src/main/java/datart/server/service/impl/StoryboardServiceImpl.java

storyboard permission bugfix

---

frontend/src/app/components/ChartGraph/BasicDoubleYChart/config.ts

fix: DoubleY chart typos

---

core/src/main/java/datart/core/mappers/ext/RelWidgetWidgetMapperExt.java
server/src/main/java/datart/server/service/impl/DashboardServiceImpl.java

补充缺失的@Override注解和去掉无用的引用包

---

core/src/main/java/datart/core/mappers/ShareMapper.java

fix update share permission Not effective bug

fix update share permission

---

core/src/main/java/datart/core/mappers/ShareMapper.java
server/src/main/java/datart/server/service/impl/ShareServiceImpl.java

修复分享链接修改不生效问题以及修改成功后再次点击操作按钮响应体返回信息不全

fix: update share permission failure and return information loss #2109
