running-elephant/datart

bin/datart-server.sh

`readlink -f` does not exist on MacOS, So change the method of getting absolute path to be compatible with macos。
In addition, the conversion line of the `data-server.sh`  in the provided installation zip file is in windows format( with CRLF line terminators) , so the script CANNOT be run on Unix or Linux .

Startup script compatible with MacOS

---

frontend/craco.config.js
frontend/src/app/pages/DashBoardPage/components/WidgetProvider/WidgetMethodProvider.tsx
frontend/src/app/pages/DashBoardPage/pages/Board/slice/types.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/SettingJumpModal/index.tsx

- 配置跳转，支持配置 URL
- HTTP URL 支持相对地址和绝对地址。如果datart 分享出去的链接，建议配置相对地址。防止服务器迁移后无法使用
- 这样可以解决曲线先解决一下分享出去无法跳转的问题。原有跳转方式保留
本人非 React专业方向 ，代码可能比较粗糙，如有问题，请官方优化一下，哈哈

Feature jump for http url

---

frontend/src/app/components/FormGenerator/Customize/ConditionStylePanel/add.tsx
frontend/src/app/components/FormGenerator/Customize/ConditionStylePanel/index.tsx
frontend/src/app/components/FormGenerator/Customize/ConditionStylePanel/type.ts
frontend/src/app/components/FormGenerator/Customize/ListTemplatePanel.tsx
frontend/src/app/components/FormGenerator/Customize/index.ts
frontend/src/app/components/FormGenerator/Layout/CollectionLayout.tsx
frontend/src/app/components/FormGenerator/Layout/GroupLayout.tsx
frontend/src/app/components/FormGenerator/Layout/ItemLayout.tsx
frontend/src/app/components/FormGenerator/types.ts
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartGraph/BasicTableChart/BasicTableChart.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartGraph/BasicTableChart/conditionStyle.ts
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartGraph/BasicTableChart/config.ts
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartGraph/FenZuTableChart/config.ts
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartGraph/MingXiTableChart/config.ts
frontend/src/app/pages/ChartWorkbenchPage/models/Chart.ts
frontend/src/app/types/ChartConfig.ts
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

大概思路：
基于现有的`json config`配置递归渲染节点的逻辑。插入条件格式的json配置项，并在其循环递归之处引入`条件格式`的配置器。
table相关基于现有components逻辑，增加对其条件格式样式的补充。
界面效果：
预览效果
控制器效果
编辑效果

feat: table add condition style. issue #259

---

frontend/src/app/pages/MainPage/index.tsx

必现操作
1.点击datart Icon 会闪烁404
原因
useEffect的原因，对于‘/’路由必然会有一瞬间的匹配失败，从而导致进入了404匹配项。
解决方式
放弃useEffect劫持方式，通过Route劫持然后Redirect，直接从界面渲染源头解决
问题展示

fix: 修复闪烁404的问题

---

frontend/src/utils/utils.ts

复现步骤
1.新建一个数据源和目录
2.将数据源移动新建好的目录下
3.删除数据源
4.删除目录
5.进入回收站
6.页面报错
bug场景

fix: 删除文件及其目录之后回收站无法打开

---

frontend/src/app/pages/DashBoardPage/components/WidgetToolBar/WidgetActionDropdown.tsx

重现步骤
1.新建一个数据视图  不要进行编辑 保证该视图图表为空
2.找一个仪表盘
3.“添加已有数据图表”，选中刚刚新建的那个视图
4.界面崩溃

fix: 数据视图为空时 仪表盘添加该数据视图 页面崩溃

---

frontend/src/app/components/ChartGraph/BasicBarChart/BasicBarChart.tsx
frontend/src/app/components/ChartIFrameContainer/ChartIFrameContainer.tsx
frontend/src/app/components/ChartIFrameContainer/ChartIFrameEventBroker.ts
frontend/src/app/components/ChartIFrameContainer/ChartIFrameLifecycleAdapter.tsx
frontend/src/app/hooks/useI18NPrefix.ts

console.log(
`translator ---> `,
context?.translator?.('common.showAxis'),
context?.translator?.('viz.palette.graph.names.barChart'),
);

feat(chart): add i18n translater to chart lifecycle

---

frontend/src/app/components/ChartGraph/BasicRichText/ChartRichTextAdapter.tsx
frontend/src/app/components/ChartGraph/ScoreChart/ScoreChart.tsx

本次pr修复了三个问题
- 翻牌器中心有蓝色小点，鼠标移动到上方会变大。
查阅代码，发现翻牌器的实现是借助了scatter图表，通过label展示实现的，所谓的蓝色小点其实是默认的一个scatter元素，控制下symbolSize即可
- 翻牌器无法显示**0**
**||** 运算符，吃掉**0**的问题，判断类型处理一下即可
- 富文本无法显示**0**
富文本使用的react-quill插件，而value使用了**Delta**格式，查阅[官方文档](http://github.com/quilljs/delta/#insert-operation)/[TS类型](https://github.com/quilljs/delta/blob/main/src/Delta.ts#L27)可知，insert的值只对string及特定obj友好。所以在把number转为string

fix: 修复翻牌器/富文本的部分问题

---

frontend/src/app/components/ChartGraph/BasicRichText/ChartRichTextAdapter.tsx

图表-富文本编辑器添加链接，tooltip 页面边缘遮挡；

---

frontend/src/app/pages/MainPage/pages/ViewPage/Main/Editor/SQLEditor.tsx

问题场景：
1.进入views sql编辑页面，然后输入**sel**，monaco会补全提示**SELECT**,当前是正常情况
2.此时直接通过侧边栏进入vizs页面，不做任何事情
3.再次重复步骤1，会发现输入**sel**,**SELECT**会多次注册,步骤1和步骤2重复操作10次，自动补全就会重复注册10次。
解决思路：
从views切换到vizs，**EditorContext**组件被销毁，变量会被销毁，所以二次进入views时，其**editorCompletionItemProviderRef**值为undefined，永远也无法销毁之前的自动补全。

fix: 修复editor自动补全重复注册的问题

---

frontend/src/app/pages/DashBoardPage/pages/Board/slice/index.ts

版本beta.1
事故现场：
1.在vizs页面提前挑选一个有数据的仪表盘，但是不要打开，并且保证数据没有被缓存，network开启Slow 3G。
2.打开该仪表盘，仪表盘内部的widget接口在pending的过程中，通过侧边栏切换到views页面。
3.等待接口pending完成，页面会提示异常信息。
解决方案：
vizs跳转views，vizs部分数据卸载，ajax回调逻辑找不到对应数据，应提前进行数据有效性验证。

fix: 仪表盘销毁后请求完成导致弹出errorMessage

---

frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDraggable/ChartDraggableTargetContainer.tsx

fix: Add default aggregation fields when dragging between data

fix: Add default aggregation fields when dragging between data

---

frontend/src/app/components/ChartGraph/BasicRichText/ChartRichTextAdapter.tsx

事故现场：
1.“开始分析”，选择富文本类型的图表
2.随便输入一段信息，选中，然后点击“加粗”“斜体”“下划线”，光标失焦之后可以看到，所选的三种效果已经应用成功
3.此时选中其中一部分信息，想要给“加粗”样式删除，会发现，单击“加粗”icon，无任何效果，无法删除已有的加粗效果
https://user-images.githubusercontent.com/95753485/155118968-0493a270-e9e9-46e0-a1e9-bfba20b1686d.mp4
事故分析：
ql编辑器支持toolbar自定义html，但是要符合对应结构。使用antd的Tooltip进行一次包裹，会导致其事件传递有一定的影响。

fix: 修复editor modules 因Toolbar导致点击事件无效样式无法正常清除的问题

---

frontend/src/app/components/ChartGraph/BasicTableChart/BasicTableChart.tsx
frontend/src/app/components/ChartGraph/BasicTableChart/TableComponents.tsx

1.开放了明细表的列宽拖拽功能
2.对单元格内存超出宽度之后的展示处理也进行了一定的优化(使用Tooltip)。

feat: 明细表列宽可拖拽及溢出隐藏

---

frontend/src/app/pages/DashBoardPage/components/WidgetCore/MediaWidget/RichTextWidget/index.tsx
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

在文字内容未撑满容器时，垂直对齐方式在重构前为顶部对齐，重构之后为居中对齐，以便于满足更多的使用场景（如标题）
在文字内容撑满或超过容器高度时，与重构之前没有区别
编辑交互重构为双击后弹窗编辑，弹窗为固定宽度，以便于完整显示工具栏。点击确认后保存编辑内容，点击取消不会保存

refactor: text vertical alignment of rich text media widget

---

frontend/src/app/components/VizHeader/VizHeader.tsx
frontend/src/app/components/VizOperationMenu/components/ShareLinkModal.tsx
frontend/src/app/components/VizOperationMenu/components/ShareManageModal.tsx
frontend/src/app/pages/StoryBoardPage/components/StoryHeader.tsx

fix: Close the request sharing list after entering the dashboard
Only organization managers set member permissions when creating shares

fix: Close the request sharing list after entering the dashboard

---

frontend/src/app/components/ChartDrill/ChartDrillContextMenu.tsx
frontend/src/app/components/ChartDrill/ChartDrillPaths.tsx
frontend/src/app/models/ChartDrillOption.ts
frontend/src/app/pages/MainPage/Navbar/index.tsx
frontend/src/app/pages/MainPage/pages/VizPage/ChartPreview/ChartPreview.tsx
frontend/src/app/pages/SharePage/ChartForShare.tsx
frontend/src/app/types/ChartDrillOption.d.ts
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

- 调整钻取右键菜单交互
- 初始状态不显示上卷菜单
- 将菜单 disabled 改为不显示
- 调整“点击下钻”开关样式
- 调整按钮文字
- 添加钻取交互限制
- 钻取到最后一级仅显示上卷菜单
- 开启“点击下钻”时，钻取到最后一级点击图表元素不再发起请求

refactor:adjust drill context-menu interaction

---

frontend/src/app/components/index.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/Properties/Container.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/Properties/DataModelTree/DataModelBranch.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/Properties/DataModelTree/DataModelNode.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/Properties/DataModelTree/DataModelTree.tsx

- 移除了列权限设置按钮
- 将类型与分类设置按钮放到了字段头部的图标上
- 给模型层级中的字段添加了独立删除按钮
- 样式优化

refactor: data model tree style improvement

---

frontend/src/app/pages/DashBoardPage/utils/index.ts
frontend/src/app/utils/chartHelper.ts

调用链   task  ->   ChartDataRequestBuilder   ->  getRuntimeDateLevelFields  -> updateBy -> immer 
导致 task build出来的 代码 包含immer和process.env 相关代码后端无法执行。
方案1
这里我改了 getRuntimeDateLevelFields 里面的代码 把updateBy 去掉了 CloneValueDeep 代替 。最终build出来的task代码就不包含 immer和process.env 。
方案2 
当然 也可以 直接在 ChartDataRequestBuilder 里面不去使用 getRuntimeDateLevelFields。在ChartDataRequestBuilder 自己实现getRuntimeDateLevelFields 的相关逻辑转换而不使用 updateBy 。

hotfix: getRuntimeDateLevelFields for task function

---

data-providers/jdbc-data-provider/src/main/resources/jdbc-driver.yml
data-providers/src/main/java/datart/data/provider/calcite/dialect/PostgresqlSqlDialectSupport.java

增加了postgresql的SqlDialect类，实现了FetchAndOffsetSupport接口，修改了对应的配置文件。使postgresql支持分页。解决了查询时拉取全量数据至本地的问题。

解决了postgresql连接类型查询时不支持分页的问题

---

frontend/src/app/components/FormGenerator/utils.ts

removeSomeObjectConfigByKey 对 options 错误的转换导致下拉框多选失效
```
{
label: 'style.autoMergeFields',
key: 'autoMergeFields',
comType: 'select',
options: {
mode: 'multiple',
...
```

fix: object key

---

frontend/src/app/models/ChartDataRequestBuilder.ts
frontend/src/app/models/__tests__/ChartDataRequestBuilder.test.ts

基本保留现有实现，只改一条：在预览页面用户运行时操作某一列排序时、预设的排序条件失效，仅该列排序条件生效；当运行时排序取消时，预设条件生效。

fix: chart sorter

---

frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDraggable/ChartDraggableTargetContainer.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDraggable/utils.ts

ChartDraggableTargetContainer.tsx file does not pass currentConfig parameter when calling getDefaultAggregate

fix:  field no auto aggregation

---

frontend/src/app/components/Tree/index.tsx
frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDataViewPanel/components/ChartComputedFieldSettingPanel.tsx
frontend/src/app/pages/DashBoardPage/components/WidgetComponents/WidgetDropdownList.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/LayerPanel/LayerTree.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/LayerPanel/LayerTreeItem.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/LayerPanel/LayerTreePanel.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/Outputs/Results.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/Properties/ColumnPermissions.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/Properties/Resource.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/StructView/components/SelectDataSource.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/Workbench.tsx
frontend/src/locales/zh/translation.json

1. 调整全局树组件样式，给叶子节点添加 · 前缀，避免空白缩进视觉不协调
2. 优化数据视图中数据库表选择器树组件样式
3. 修复数据视图中右侧数据库信息面板字段类型图标显示问题
4. 优化仪表板编辑器左侧组件列表样式

chore: tree component style improvement

---

frontend/src/app/pages/MainPage/pages/SchedulePage/EditorPage/index.tsx

问题描述：定时任务模块，当先点击运行中状态的任务（此状态保存按钮为禁用状态），再点击新建任务，右上方保存按钮依旧为禁用状态，不合理，正常新增任务是支持保存操作的；
修复方式：当新建任务时，根据isAdd值，初始化active的值，具体代码如下：
const active = useMemo(() => {
return isAdd ? false : editingSchedule?.active;
}, [editingSchedule, isAdd]);

修复定时任务模块，当先点击运行中的任务，再点击新建任务，右上方的保存按钮依旧是禁用状态；已修复为新建任务时初始化active的状态为false

---

frontend/src/app/pages/MainPage/pages/VizPage/slice/thunks.ts

fix: Add default value to dataset when there is no view id

fix: Add default value to dataset when there is no view id

---

frontend/src/app/hooks/useStateModal.tsx

问题视频
https://user-images.githubusercontent.com/95753485/178678921-2f7bdc5e-4254-4e4a-96bf-acafe1f39c43.mp4

fix: 修复指标操作格式之后数据混乱的问题

---

frontend/src/app/pages/MainPage/pages/ViewPage/Main/Properties/Variables.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/SaveForm.tsx

另外，右边这几个面板的搜索功能都没有忽略大小写，我感觉忽略大小写用起来更方便，可以改吗，可以的话我明天改好再提个pr

fix: 数据视图-变量配置-搜索功能、数据视图-设置-有效期不能为负值

---

frontend/src/app/components/ChartGraph/BasicPieChart/BasicPieChart.tsx
frontend/src/app/types/ChartConfig.ts

参考这个页面写的：https://echarts.apache.org/examples/zh/editor.html?c=pie-doughnut
鼠标移到一个色块上才能显示。
#1080

fix: 饼图、环形图，标签位置选“中心”时不显示

---

frontend/src/app/pages/DashBoardPage/components/Widgets/ControllerWidget/Controller/CheckboxGroupController.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/ValuesOptionsSetter/AssistViewFields.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/ValuesOptionsSetter/ValuesOptionsSetter.tsx
frontend/src/app/pages/MainPage/pages/ViewPage/Main/Properties/Resource.tsx
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

fix: Add search when view and field are selected in regular controller #1572

fix: Add search when view and field are selected in regular controller #1572

---

server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java

我发现在1.0.0-beta.3中，保存view的时候，列的信息中   columns -》 name 的值是字符串来的，但是到了1.0.0-beta.4 中 columns -》 name 的值是数组来的，然后这部分DataProviderServiceImpl#parseSchema  在 1.0.0-beta.4 版本去执行之前 版本所保存的view，关联的datachart图就会报解析错误了，因为之前的代码解析是默认将name当做数组解析了，所以导致name为字符串的时候就报错了。
我修改的代码就是判断一下类型，是数组的才用数组解析，否则都获取字符串对象
具体的报错信息如下：
```
ERROR datart.server.service.impl.DataProviderServiceImpl : view model parse error
com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2dt
at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1487)
at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1373)
```
目前这个影响的主要是解析parseSchema 这里，应该不影响界面功能，不过好像聚合那里用到schema，可能会影响聚合
麻烦大佬有空的时候，帮忙code review一下代码了

修复view 中解析配置的schema，columns -》 name的问题

---

server/src/main/java/datart/server/service/UserService.java
server/src/main/java/datart/server/service/impl/ExternalRegisterServiceImpl.java
server/src/main/java/datart/server/service/impl/UserServiceImpl.java

在ldap/oauth2认证时会初始化用户密码并生成passwordToken, 然后调用注册接口, 此时注册接口会解析jwt的密码并二次加密, 这时存入数据库的密码和认证时初始化的密码不一致,导致登录时比较hashCode会抛出"用户已修改密码"错误

fix: 修复#1826 issue, ldap/oauth2认证自动注册用户时,秘钥加密两次导致鉴权失败("用户已修改密码"错误)

---

data-providers/data-provider-base/src/main/java/datart/data/provider/jdbc/DataTypeUtils.java
data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java

新建数据视图时如果数据源是PG类，数据模型的字段类型很多解析不出来，因为使用了columnTypeName（String)作为解析，PG存在int4、int8之类的名称，使用jdbc columnType(int)会更加通用
data type in data model is wrong when create data view, it cause by 
use jdbc column type name(String) to parse, this method cannot parse correct when  type name  like int4、int8, change to use use jdbc column type(int),is more general

feat: fix parse wrong column type when parse sql for PostgreSQL(修复新建数据视图时解析数据模型字段类型不正确)

---

server/src/main/java/datart/server/service/impl/DashboardServiceImpl.java

修复资源迁移-》数据导入的问题，当dashboard页面中包含 联动组件（两个组件相互关联）的时候，导出该dashboard资源后，再导入到其他的组织的时候会报错
例如在demo环境，导出导入这个页面就会报错 
http://datart-demo.retech.cc/organizations/b82a1357face4342b678070ab170fe84/vizs/91df22a74354423998168c6da4b7f35a
报错信息如下：
n### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'source_id' cannot be null
我看到的设置导入 资源，存储新旧widget的id的时候，顺序不对，需要修改先保留新旧widget id，再设置原widget对象的
另外 ralation 对象的id，如果之前导入过一次，然后策略还是选择新增的时候，这里的relation id就要设置重新设置，不然再次导入相同资源，策略为新增的时候也会报错
麻烦大佬帮忙code review一下提交的pr代码是否有问题了

fix: import resource problem, when dashboard contain relation

---

server/src/main/java/datart/server/service/impl/FolderServiceImpl.java

在使用资源迁移的功能的时候，我导出一个包含目录的仪表板 & 数据图表 资源，然后，导入到其他组织的时候，发现找不到这些资源了
看了一下代码，应该是导入的时候，插入新的目录时，没设置新的目录组织id为新的组织id，导致在新的组织id中找不到对应目录；我这里就在插入新目录的时候，重新设置了一下组织id
可以用demo 环境中这个导出，再导入其他组织看
http://datart-demo.retech.cc/organizations/906b5ecb8ade4d6d88a708c26ffd76b5/vizs/32f856a507ab4d70a184b2ed83b67a17
麻烦大佬帮忙 review看看了

fix: 修复资源迁移导入目录的时候没设置目录新的组织id问题

---

frontend/src/app/migration/__tests__/migrateChartConfig.test.ts
frontend/src/app/pages/DashBoardPage/components/Widgets/ControllerWidget/Controller/TreeController.tsx
frontend/src/app/pages/DashBoardPage/components/Widgets/ControllerWidget/ControllerWidgetCore.tsx
frontend/src/app/pages/DashBoardPage/pages/Board/slice/thunk.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/TreeSetter/TreeSetter.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/TreeTypeSetter/TreeTypeSetter.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/TreeTypeSetter/index.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/ValuesSetter/ValuesOptionsSetter/ValuesOptionsSetter.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/ControllerConfig/index.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/index.tsx
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/types.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/components/ControllerWidgetPanel/utils.ts
frontend/src/app/pages/DashBoardPage/pages/BoardEditor/slice/thunk.ts
frontend/src/app/pages/DashBoardPage/utils/widget.ts
frontend/src/locales/en/translation.json
frontend/src/locales/zh/translation.json

dashboard的树控制器支持了两种数据模型
一种是树形控件：类似于这样的数据，parentId和id对应,无限嵌套的数据
一种是树选择：可以参考以下数据, name_level1是顶级目录，name_level2 是name_level1的子目录，name_level3 是name_level2的子目录
展示截图：

feat: Added two tree controllers for dashboard

---

core/pom.xml

更新 fastjson的版本为1.2.83，之前的版本 有在特定场景下可以绕过autoType关闭限制的漏洞
fastjson 发版说明中有说
https://github.com/alibaba/fastjson/releases/tag/1.2.83

refactor: update fastjson version fix autoType bug

---

server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java

我看代码中解析的view的列信息的时候，使用了HashMap ，然后 fastjson 解析的时候也是默认使用了无序的方式，这样解析出的列信息是无序的，但是在view的model属性中存储的列信息是有顺序的，前端解析的时候也是有顺序的，所以我这里优化了一下代码，把后端解析的列信息时也返回有序的，目前不知道有什么地方会后端需要用到有序的地方，但是我觉得保持跟前端解析顺序一样还是比较好
麻烦大佬帮忙code view 一下了

refactor: parse schema column order

---

security/src/main/java/datart/security/manager/shiro/ShiroSecurityManager.java

fix: unbind subject before run as other user ； fix download excel or csv
关联这个bug，在runAs之前解绑当前线程的 subject，以免主线程退出后影响该线程数据，导致下载的时候可能出现用户为空，空指针异常，使用 [Drafthj](https://github.com/Drafthj) 的评论方法解决
https://github.com/running-elephant/datart/issues/2018

fix: unbind subject before run as other user ； fix download excel or csv

---

server/src/main/java/datart/server/common/PoiConvertUtils.java

兼容下载excel并且可视化列配置为空的时候，下载到空表头问题
有时候前端会传了一个不存在的datachartId 过来的，这个时候获取到可视化配置就会为空，
对应这里的问题  https://github.com/running-elephant/datart/issues/2018
[HP-jackZhang](https://github.com/HP-jackZhang) commented [issuecomment](https://github.com/running-elephant/datart/issues/2018#issuecomment-1480731387)
至于为什么前端会传了一个不存在的datachartId 过来，是因为目前前端在下载的时候判断可视化组件为widget还是datachart的时候，使用了id是否包含widget来来判断，这种判断在可视化组件为复制的情况下是错误，应该根据 originalType 来判断是widget还是datachart才会更准确

refactor: Compatibility download with null chartColumns

---

server/src/main/java/datart/server/service/impl/ViewServiceImpl.java

我在测试资源导入的时候发现，如果view 包含目录导入的时候，view 展示不出来
看了代码发现是导入资源view的时，没重新更新 parentId 导致的，导致view虽然导入进去了，但是因为 parentId  关联不上，所以显示不出来
我这个pr，将导入view的时候，修改为先设置新的目录id，然后再设置view的相关信息，然后重新设置parentId 
麻烦大佬帮忙code view 一下了

 修复资源迁移导入view的时候，没设置parentId为新的问题

---

server/src/main/java/datart/server/service/impl/DataProviderServiceImpl.java

最近我在二开datart的时候，发现有时候获取不到view的列信息，后面发现是原解析view列信息的没完全兼容旧版情况，name 属性可能为null的情况
例如下面的例子：
http://datart-demo.retech.cc/organizations/1306a51ec4a44620bdb0fffca8656a1f/views/dc3b88e372cd405d88268715e93bfb5a
这个view的names 中就是不存在name属性，如果解析会返回null的
解析view的列信息问题，在旧版datart 的时候 view的列信息中 columns 中不存在name 属性字段的，
原代码中 直接 通过 
```java
names = new String[]{item.getString("name")};
//  ..........
Column column = Column.of(ValueType.valueOf(item.getString("type")), names);
```
如果之前版本中name 不存在，则得到的 column 对象一直为null，返回也是只有一个null对象，而得不到的实际view的列信息，我这个pr 补充一下空的判断，兼容一下旧版datart情况

兼容旧版datart 解析列名时，获取不到view实际列的问题

---

core/src/main/java/datart/core/mappers/ext/RelWidgetElementMapperExt.java
core/src/main/java/datart/core/mappers/ext/RelWidgetWidgetMapperExt.java
server/src/main/java/datart/server/service/impl/DashboardServiceImpl.java

优化代码，优化获取widget的关联信息，修改为批量从数据获取到关联信息
看原代码获取到widget的关联信息是通过遍历widget，然后每次循环到数据库中获取的关联信息的，这样当要遍历的widget比较多的时候，可能会比较慢
我优化了这部分代码，先在遍历widget信息之前先批量获取从数据库获取到widget的关联信息，然后再在循环中赋值，这样就不用查询多次数据库，提高处理速度

优化获取widget的关联信息，修改为批量从数据获取到关联信息

---

data-providers/jdbc-data-provider/src/main/java/datart/data/provider/jdbc/adapters/JdbcDataProviderAdapter.java

Fix cache errors when there is column permission control, the same sql for different views, and the data source does not support paging sql
修复缓存数据可能错误的问题，当有下面的情况，缓存的数据可能是错误，因为的没有只是根据sql缓存
1. 当有列权限控制   (目前列权限是根据不同角色控制的，如果view设置了缓存，那样所有人都会看到相同的缓存的，而不是根据设置的列权限，谁能看到不同权限数据)
2. 不同数据源不同view相同sql （不同数据源 时候即使sql一样，数据也可能不一样，如果单单针对sql缓存了就会返回相同缓存数据）
3. 数据源不支持分页sql的时候（目前在判断的分页到时候，会有两种情况数据源，一个是sql支持分页的，这种是会修改sql支持分页参数，这个时候对分页缓存是没问题的；另一种是sql不支持分页，代码中是通过Connection statement 实现的，这种情况下通过sql去缓存数据，会导致不同分页参数的请求都获取到同一个缓存数据，presto 数据源就是这样）
目前我改进的方法：在生成缓存key的时候，加上列权限字段列表，viewId和分页参数 ，这样就可以避免以上三种情况导致缓存错误。
麻烦帮忙code review 了，或看看是否有什么问题了

fix: fix cache data may errors 

---

frontend/craco.config.js
frontend/src/app/AppRouter.tsx
frontend/src/app/pages/DashBoardPage/utils/index.ts
frontend/src/app/pages/SharePage/Chart/Router.tsx
frontend/src/app/pages/SharePage/Dashboard/Router.tsx
frontend/src/app/pages/SharePage/StoryPlayer/Router.tsx
frontend/src/app/utils/fetch.ts
frontend/src/globalConstants.ts
frontend/src/utils/request.ts

Configure public path easily.
Steps
1. Server: add `server.servlet.context-path=YOUR_PUBLIC_PATH` to `datart.conf`
2. Frontend: modify npm script `"build": "cross-env PUBLIC_URL=YOUR_PUBLIC_PATH GENERATE_SOURCEMAP=false craco build"`

refactor: Improving public path support
